os: linux
dist: xenial
sudo: require
language: haskell

matrix:
  include:
  - env:
    - CABAL=2.2   GHC=8.4.4
    - CABAL=2.4   GHC=8.6.5
  allow_failures:
  - env:
    - CABAL=3.0   GHC=8.8.1

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABAL ghc-$GHC
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:$PATH

install:
  - cabal --version
  - ghc --version
  - travis_retry cabal new-update
  - cabal new-install --lib

script:
  - cabal new-configure --enable-tests
  - cabal new-build
  - cabal new-test
