version: 1.0.{build}
platform: x64
install:
- ps: >-
    choco install haskellplatform -version 2014.2.0.0 -y

    $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\bin"

    $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\lib\extralibs\bin"

    $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\mingw\bin"

    cabal update

build_script:
- ps: >-
    cabal install --enable-tests

    cabal configure --enable-tests

    cabal build

test_script:
- ps: cabal test
